[package]
name = "solana_vanity_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.0"
bs58 = "0.4"
rayon = "1.5"
num_cpus = "1.16"
parking_lot = "0.12"
tiny-bip39 = "0.8.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
